version: 1.0.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
test_script:
- ps: dotnet test XUnitTest/XUnitTest.csproj
artifacts:
- path: '**/Aliq.*.nupkg'
build:
  project: Aliq.sln
  verbosity: minimal
after_build:
 - ps: buildAliqcomms.ps1